### ISSUE TITLE
feat(color): Support HexCode in suffix color.

### ISSUE THREAD

**Issue by Sraconni** [ArtformGames/UserSuffix#5]
### **Description**

Support HexCode in suffix color.

### **Source**

HexCode looks better than standard colors in suffix, and players are also more prefer to use HexCode to customize their suffixes.

### **Examples** _(Optional)_

No

### **AddItional details**

No

**Comment by CarmJos** [comment]
Please try this build: https://github.com/ArtformGames/UserSuffix/actions/runs/8082973651

**Comment by Sraconni** [comment]
> Please try this build: https://github.com/ArtformGames/UserSuffix/actions/runs/8082988472
> 
> Notice: You should delete the exist database table first.

HexCode support seems to be great, but there seems to be some problems with mysql. When switching servers or exiting the server and rejoining, the suffix data will be cleared from the database.

![image](https://github.com/ArtformGames/UserSuffix/assets/108390647/503dce9b-c193-440b-9704-b7c36a0a4a54)

**Comment by CarmJos** [comment]
Try https://github.com/ArtformGames/UserSuffix/actions/runs/8095546617

**Comment by Sraconni** [comment]
> Try https://github.com/ArtformGames/UserSuffix/actions/runs/8095546617

Looks great, everything fine :3
